version: '3.7'

services:
  # region infrastructure
  db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      backend:
        aliases:
          - "postgres"
  configserver:
    image: configserver:latest
    ports:
      - "8071:8071"
    environment:
      - "SERVER_PORT=8071"
    networks:
      backend:
        aliases:
          - "configserver"
  eurekaserver:
    image: eurekaserver:latest
    ports:
      - "8070:8070"
    environment:
      - "SERVER_PORT=8070"
    networks:
      backend:
        aliases:
          - "eurekaserver"
  gatewayserver:
    image: gatewayserver:latest
    ports:
      - "8072:8072"
    environment:
      - "SERVER_PORT=8072"
      - "SPRING_CONFIG_IMPORT=configserver:http://configserver:8071"
    networks:
      backend:
        aliases:
          - "gatewayserver"
    depends_on:
      - "configserver"
      - "licensingservice"
      - "organizationservice"
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      backend:
        aliases:
          - "zookeeper"
  kafkaserver:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - "KAFKA_ADVERTISED_HOST_NAME=kafka"
      - "KAFKA_ADVERTISED_PORT=9092"
      - "KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181"
      - "KAFKA_CREATE_TOPICS=organizations:1:1"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - "zookeeper"
    networks:
      backend:
        aliases:
          - "kafka"
  redisserver:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      backend:
        aliases:
          - "redis"
  # endregion infrastructure

  # region microservices
  licensingservice:
    image: licensing-service:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
    ports:
      - "8180:8080"
    environment:
      - "SPRING_CONFIG_IMPORT=configserver:http://configserver:8071"
    networks:
      backend:
        aliases:
          - "licenseservice"
    depends_on:
      - "configserver"
      - "eurekaserver"
      - "db"
      - "redisserver"
  organizationservice:
    image: organization-service:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
    ports:
      - "8181:8080"
    environment:
      - "SPRING_CONFIG_IMPORT=configserver:http://configserver:8071"
    networks:
      backend:
        aliases:
          - "organizationservice"
    depends_on:
      - "configserver"
      - "eurekaserver"
      - "db"
  #endregion microservices

networks:
  backend:
    driver: bridge

volumes:
  db:
    driver: local
